CREATE TABLE EMPLOYEE(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              CHECK( AGE >= 18),
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

INSERT INTO EMPLOYEE (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'SAM', 32, 'Ahmedabad', 2000.00 );

INSERT INTO EMPLOYEE (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'JOHN', 25, 'Delhi', 1500.00 );

INSERT INTO EMPLOYEE (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'ARIANA', 23, 'Kota', 2000.00 );

INSERT INTO EMPLOYEE (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'TOM', 25, 'Mumbai', 6500.00 );

INSERT INTO EMPLOYEE (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'TONY', 27, 'Bhopal', 8500.00 );

INSERT INTO EMPLOYEE (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'ROSE', 22, 'MP', 4500.00 );

SELECT * FROM EMPLOYEE;

CREATE TABLE EMPLOYEE_LOG(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              CHECK( AGE >= 18),
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);


create or replace trigger employeeTrigger
Before Update on EMPLOYEE
FOR EACH ROW
when (new.salary>0 )
declare
Begin 
    INSERT INTO EMPLOYEE_LOG(ID,NAME,AGE,ADDRESS,SALARY)
    VALUES (:old.id,:old.name,:old.age,:old.address,:old.salary);
end;


SELECT * FROM EMPLOYEE_LOG;

Update EMPLOYEE
Set SALARY = 3000
where id = 3;


SELECT * FROM EMPLOYEE_LOG;

SELECT * FROM EMPLOYEE;

